#!/bin/bash

###
## cssh
## http://github.com/c3w/cssh
## Purpose: Changes OSX Terminal Profile to n per machine.  Also supports tunneling #currently commented out
## Create your Terminal profiles, under Terminal Preferences
## alias ssh="~/bin/cssh"

#TUNNEL_HOST="dev"
DEFAULT_PROFILE="default"
PORT="22"
SUFFIX="mydomain.tld"
USER="myusername"

function setTerm() {
PROFILE=${1}
osascript << __EOF__
        tell app "Terminal" to set current settings of first window to settings set "$PROFILE"
__EOF__
}

case "${1}" in
        web*|search*|cache*)
                PROFILE="webserver"
                ;;
        jobs*|vpn*)
                PROFILE="admin"
                ;;
        dev*)
                PROFILE="development"
                ;;
        smtp*)
                PROFILE="mailserver"
                ;;
        db*)
                PROFILE="database"
                ;;
	*)
		PROFILE="default"
		SUFFIX=""
esac

setTerm "${PROFILE}"
	if [ "${TUNNEL_HOST}" ]; then {
		ssh -t ${USER}@${TUNNEL_HOST} -p ${PORT} "ssh -t root@${*}.${SUFFIX}"
	} else {
        	ssh -p ${PORT} ${USER}@${*}.${SUFFIX}
	}; fi
setTerm ${DEFAULT_PROFILE}
